---
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/' # Location of package manifest
    schedule:
      interval: 'monthly'
    groups:
      dev-dependencies: # i.e., all deps of this project
        patterns:
          - '*'
