---
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
    groups:
      dev-dependencies: # i.e., all deps of this project
        patterns:
          - "*"
