---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Lint Codebase

#############################
# Start job on PR to master #
#############################
on:
  pull_request:
    branches: [master]

####################
# Describe the job #
####################
jobs:
  build:
    # Name the job
    name: Lint Codebase
    # Set agent
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ######################
      # Check out codebase #
      ######################
      - name: Check out code
        uses: actions/checkout@v3
        with:
          # Full history needed for list of changed files within `super-linter`
          fetch-depth: 0

      ###############################
      # Run linter against codebase #
      ###############################
      - name: Lint Codebase
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_CSS: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          FILTER_REGEX_EXCLUDE: .*(\.min\.|sw\.js|workbox).*
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
