---
name: Lint Codebase

on:
  pull_request:
    branches: [master]

jobs:
  build:
    name: Lint Codebase
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Codebase
        uses: super-linter/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_CSS: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          FILTER_REGEX_EXCLUDE: .*(\.min\.|sw\.js|workbox).*
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
