---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Lint Codebase

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

###########################################
# Start the job on pull request to master #
###########################################
on:
  pull_request:
    branches: [master]

###############
# Set the job #
###############
jobs:
  build:
    # Name the job
    name: Lint Codebase
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      #########################
      # Checkout the codebase #
      #########################
      - name: Checkout Code
        uses: actions/checkout@v2

      ###############################
      # Run linter against codebase #
      ###############################
      - name: Lint Codebase
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: true
          FILTER_REGEX_EXCLUDE: .*(\.min\.|sw\.js|workbox).*
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
